/**
 * Read model contract guard가 server-provided value/order/source를 보존하는지 검증하는 sentinel fixture다.
 * 날짜순, rank순, severity순으로 다시 정렬하면 테스트가 바로 실패하도록 일부러 자연 순서와 다른 값을 섞어 둔다.
 */

import type {
  ApplicationDashboardReadModel,
  DashboardSnapshotDetailReadModel,
  DashboardSnapshotMarkerReadModel,
  InstanceDashboardReadModel,
  InstanceEvidenceReadModel,
  InstanceSnapshotTrendReadModel,
  OperationalEventHistoryReadModel,
} from "./read-model-types.js";

export const CONTRACT_PROJECT_ID = "11111111-1111-1111-1111-111111111111";
export const CONTRACT_APPLICATION_ID = "22222222-2222-2222-2222-222222222222";
export const CONTRACT_INSTANCE_ID = "instance-contract-a";
export const CONTRACT_SNAPSHOT_ID = "33333333-3333-3333-3333-333333333333";

export const dashboardContractFixture: ApplicationDashboardReadModel = {
  schemaVersion: "dashboard_read_model.v1",
  mode: "live",
  generatedAt: "2026-06-09T00:05:00Z",
  application: {
    projectId: CONTRACT_PROJECT_ID,
    applicationId: CONTRACT_APPLICATION_ID,
    name: "orders-api",
    environment: "prod",
    lastAcceptedBucketAt: "2026-06-09T00:04:30Z",
    lastHealthyAt: null,
    sourceWindow: {
      current: {
        startUtc: "2026-06-08T23:35:00Z",
        endUtc: "2026-06-09T00:05:00Z",
      },
      baseline: null,
    },
    freshness: {
      lastObservedAt: "2026-06-09T00:04:30Z",
      staleAt: "2026-06-09T00:06:00Z",
      downAt: "2026-06-09T00:07:30Z",
    },
  },
  window: {
    type: "recent_30_minutes",
    startUtc: "2026-06-08T23:35:00Z",
    endUtc: "2026-06-09T00:05:00Z",
  },
  thresholds: {
    minimumRequestCount: 30,
    errorRate: 0.05,
    slowShareOver500ms: 0.2,
    datasourcePoolUsage: 0.85,
    cpuUsage: 0.85,
    heapUsage: 0.9,
  },
  operatorSummary: {
    headline: "서버가 계산한 운영자 요약입니다.",
    primaryProblemCode: "server-rule-b",
    firstLookText: "서버가 준 first look queue를 순서대로 표시합니다.",
  },
  dataQuality: {
    state: "sufficient",
    requestCount: 91,
    minimumRequestCount: 30,
    lastObservedAt: "2026-06-09T00:04:30Z",
    limitations: [
      "baseline_comparison_not_used_for_mvp",
      "sourceWindow.baseline_null_public_read_model",
    ],
  },
  state: {
    code: "degraded",
    label: "주의 필요",
    rationale: "서버가 이미 판단한 상태 설명",
    recommendedAction: "서버가 제공한 조치 문구를 표시합니다.",
    scope: "application",
  },
  starterConnection: {
    statusSource: "starter_heartbeat",
    lastHeartbeatAt: "2026-06-09T00:04:50Z",
    lastHeartbeatStatus: "received",
    connectionMeaning: "starter_connected",
    stateImpact: "none",
  },
  signals: {
    red: {
      requestCount: 91,
      errorCount: 7,
      errorSemantic: "server_error_5xx",
      errorRate: 0.0769,
      slowCountOver500ms: 21,
      slowShareOver500ms: 0.2308,
      latencyEvidenceStatus: "available",
    },
    use: {
      datasourcePoolUsage: {
        max: 0.62,
        threshold: 0.85,
        status: "normal",
        observedAt: "2026-06-09T00:04:30Z",
      },
      cpuUsage: {
        max: 0.72,
        threshold: 0.85,
        status: "normal",
        observedAt: "2026-06-09T00:04:30Z",
      },
      heapUsage: {
        max: 0.91,
        threshold: 0.9,
        status: "threshold_hit",
        observedAt: "2026-06-09T00:04:30Z",
      },
    },
  },
  stateReasons: [
    {
      type: "application_latency",
      severity: "warning",
      scope: "application",
      target: null,
      reasonCode: "application_slow_share_high",
      operatorText: "서버가 계산한 state-changing reason입니다.",
    },
  ],
  attentionEvidence: [
    {
      type: "endpoint_server_error",
      severity: "attention",
      scope: "endpoint",
      target: "POST /a-contract",
      reasonCode: "endpoint_server_error_observed",
      affectsLifecycleState: false,
      operatorText: "서버가 계산한 attention-only evidence입니다.",
    },
  ],
  firstLookCandidates: [
    {
      rank: 2,
      type: "endpoint",
      target: "GET /z-contract",
      reasonCode: "server_first_look_z",
      source: "endpointPriority",
      operatorText: "서버 제공 rank 2 후보를 첫 번째로 둡니다.",
    },
    {
      rank: 1,
      type: "resource_pressure",
      target: "heap",
      reasonCode: "server_first_look_heap",
      source: "attentionEvidence",
      operatorText: "서버 제공 rank 1 후보를 두 번째로 둡니다.",
    },
  ],
  readSemantics: {
    source: "accepted_metric_buckets",
    snapshotDetailRecalculates: false,
    markerIsStateSource: false,
    baselineComparisonUsedForMvpDecision: false,
    helperColumnsAreStateSource: false,
    histogramBucketsUsedForPercentiles: false,
    bucketDistributionSource: "accepted_bucket",
    bucketDistributionMeaning: "accepted_metric_buckets.duration_buckets_json_distribution_display_only",
    bucketEndBoundary: "bucket_end_utc > window.startUtc and bucket_end_utc <= window.endUtc",
  },
  zeroInsight: null,
  recovery: {
    isRecovering: false,
    lastHealthyAt: null,
    retryAfterSeconds: null,
    recommendedAction: null,
  },
  metrics: {
    requestCount: 91,
    errorCount: 7,
    errorRate: 0.0769,
  },
  sourceScopedPercentiles: {
    source: "starter_canonical_percentile",
    scope: "instance_bucket",
    displayPolicy: "source_scoped_points",
    aggregatePolicy: "no_average_no_max_no_merge_no_histogram_recalculation",
    status: "available",
    reason: null,
    items: [
      {
        source: "starter_canonical_percentile",
        application: "orders-api",
        environment: "prod",
        instance: CONTRACT_INSTANCE_ID,
        bucketStartUtc: "2026-06-09T00:04:00Z",
        bucketEndUtc: "2026-06-09T00:04:30Z",
        requestCount: 41,
        p95Ms: 220,
        p99Ms: 410,
      },
    ],
  },
  histogramDistribution: {
    source: "accepted_bucket",
    scope: "application",
    displayPolicy: "cumulative_bucket_distribution",
    aggregatePolicy: "display_bucket_only_no_percentile_recalculation",
    current: {
      status: "available",
      reason: null,
      totalCount: 91,
      buckets: [
        { leMs: 100, count: 7 },
        { leMs: 500, count: 70 },
        { leMs: 1000, count: 91 },
      ],
    },
    baseline: {
      status: "available",
      reason: null,
      totalCount: 80,
      buckets: [
        { leMs: 100, count: 10 },
        { leMs: 500, count: 70 },
        { leMs: 1000, count: 80 },
      ],
    },
  },
  triageCards: [
    {
      ruleId: "server-rule-b",
      severity: "warning",
      title: "서버 판단 카드",
      summary: "UI가 severity/confidence로 재정렬하지 않아야 합니다.",
      recommendation: "서버가 준 순서대로 표시합니다.",
      confidence: 0.41,
      score: 12,
      affectedEndpoint: "GET /z-contract",
      evidence: {
        requestCount: 91,
        currentErrorCount: 7,
        currentErrorRate: 0.0769,
        baselineRequestCount: null,
        baselineErrorCount: null,
        baselineErrorRate: null,
        errorRateDelta: null,
        currentSlowShare: null,
        baselineSlowShare: null,
        currentHistogram: null,
        baselineHistogram: null,
        runtimeRatio: null,
        freshnessStatusReason: null,
        sourcePercentilePoint: null,
      },
    },
  ],
  endpointPriority: [
    {
      rank: 20,
      method: "GET",
      route: "/z-contract",
      endpointKey: "GET /z-contract",
      reason: "latency_spike",
      ruleIds: ["server-rule-b"],
      confidence: 0.41,
      score: 12,
      freshness: {
        status: "current",
        lastObservedAt: "2026-06-09T00:04:30Z",
        sourceWindow: "current",
        reason: null,
      },
      evidence: {
        requestCount: 40,
        errorCount: 1,
        errorRate: 0.025,
        baselineRequestCount: null,
        baselineErrorCount: null,
        baselineErrorRate: null,
        errorRateDelta: null,
        durationBuckets: [
          { leMs: 500, count: 30 },
          { leMs: 1000, count: 40 },
        ],
        baselineDurationBuckets: null,
        slowShare: 0.25,
        baselineSlowShare: null,
        slowShareDelta: null,
        bucketDistributionSource: "accepted_bucket",
        errorEvidenceStatus: "available",
        latencyEvidenceStatus: "available",
      },
      recommendedAction: "서버 제공 rank 20 항목을 첫 번째로 둡니다.",
    },
    {
      rank: 10,
      method: "POST",
      route: "/a-contract",
      endpointKey: "POST /a-contract",
      reason: "error_spike",
      ruleIds: ["server-rule-a"],
      confidence: 0.99,
      score: 99,
      freshness: {
        status: "current",
        lastObservedAt: "2026-06-09T00:04:30Z",
        sourceWindow: "current",
        reason: null,
      },
      evidence: {
        requestCount: 51,
        errorCount: 6,
        errorRate: 0.1176,
        baselineRequestCount: null,
        baselineErrorCount: null,
        baselineErrorRate: null,
        errorRateDelta: null,
        durationBuckets: [
          { leMs: 500, count: 45 },
          { leMs: 1000, count: 51 },
        ],
        baselineDurationBuckets: null,
        slowShare: 0.11,
        baselineSlowShare: null,
        slowShareDelta: null,
        bucketDistributionSource: "accepted_bucket",
        errorEvidenceStatus: "available",
        latencyEvidenceStatus: "available",
      },
      recommendedAction: "서버 제공 rank 10 항목을 두 번째로 둡니다.",
    },
  ],
  instances: [
    {
      instanceId: CONTRACT_INSTANCE_ID,
      instanceName: "orders-api-contract-a",
      lastSeenAt: "2026-06-09T00:04:30Z",
      links: {
        evidence: `/api/projects/${CONTRACT_PROJECT_ID}/applications/${CONTRACT_APPLICATION_ID}/instances/${CONTRACT_INSTANCE_ID}/evidence`,
      },
    },
  ],
  snapshot: null,
};

export const snapshotEventsContractFixture: OperationalEventHistoryReadModel = {
  generatedAt: "2026-06-09T00:05:00Z",
  applicationId: CONTRACT_APPLICATION_ID,
  source: "dashboard_snapshots",
  horizon: {
    since: "2026-06-08T00:00:00Z",
    until: "2026-06-09T00:00:00Z",
    requestedSince: "24h",
    defaultSince: "24h",
    maxSince: "14d",
    limit: 50,
    maxLimit: 100,
    order: "occurredAt_desc",
  },
  events: [
    {
      eventId: "event-server-first",
      type: "warning",
      severity: "warning",
      title: "서버가 먼저 준 이벤트",
      summary: "발생 시각 정렬로 바꾸면 순서가 달라집니다.",
      occurredAt: "2026-06-08T01:00:00Z",
      resolvedAt: null,
      stateCode: "degraded",
      confidence: 0.3,
      snapshotId: CONTRACT_SNAPSHOT_ID,
      evidence: {
        ruleId: "server-rule-b",
        endpointKey: "GET /z-contract",
        method: "GET",
        route: "/z-contract",
        snapshotDetailAnchor: "endpoint-z",
        anchorStatus: "resolved",
      },
      links: {
        snapshot: `/api/projects/${CONTRACT_PROJECT_ID}/applications/${CONTRACT_APPLICATION_ID}/dashboard/snapshots/${CONTRACT_SNAPSHOT_ID}`,
      },
    },
    {
      eventId: "event-server-second",
      type: "critical",
      severity: "critical",
      title: "서버가 두 번째로 준 이벤트",
      summary: "severity나 occurredAt으로 재정렬하면 앞으로 올라옵니다.",
      occurredAt: "2026-06-08T23:00:00Z",
      resolvedAt: null,
      stateCode: "down",
      confidence: 0.95,
      snapshotId: "44444444-4444-4444-4444-444444444444",
      evidence: {
        ruleId: "server-rule-a",
        endpointKey: "POST /a-contract",
        method: "POST",
        route: "/a-contract",
        snapshotDetailAnchor: "endpoint-a",
        anchorStatus: "resolved",
      },
      links: {
        snapshot: `/api/projects/${CONTRACT_PROJECT_ID}/applications/${CONTRACT_APPLICATION_ID}/dashboard/snapshots/44444444-4444-4444-4444-444444444444`,
      },
    },
  ],
};

export const snapshotMarkersContractFixture: DashboardSnapshotMarkerReadModel = {
  generatedAt: "2026-06-09T00:05:00Z",
  applicationId: CONTRACT_APPLICATION_ID,
  source: "dashboard_snapshots",
  horizon: {
    since: "2026-06-08T00:00:00Z",
    until: "2026-06-09T00:00:00Z",
    requestedSince: "24h",
    defaultSince: "24h",
    maxSince: "14d",
    limit: 48,
    maxLimit: 672,
    order: "currentWindowEndUtc_asc",
  },
  emptyState: null,
  markers: [
    {
      markerId: "marker-server-second",
      snapshotId: "44444444-4444-4444-4444-444444444444",
      capturedAt: "2026-06-08T01:30:05Z",
      currentWindowEndUtc: "2026-06-08T00:30:00Z",
      type: "critical",
      severity: "critical",
      readMeaning: "stored_read_model_point",
      captureReason: "state_change",
      storedApplicationStateCode: "down",
      previousState: {
        stateCode: "active",
        source: "dashboard_snapshots",
        snapshotId: CONTRACT_SNAPSHOT_ID,
        capturedAt: "2026-06-08T01:00:00Z",
      },
      title: "서버가 두 번째로 준 마커",
      summary: "capturedAt, severity, captureReason으로 앞으로 당기면 contract 위반입니다.",
      recommendedAction: null,
      confidence: 0.98,
      primaryRuleId: "server-rule-a",
      primaryEndpointKey: "POST /a-contract",
      links: {
        snapshot: `/api/projects/${CONTRACT_PROJECT_ID}/applications/${CONTRACT_APPLICATION_ID}/dashboard/snapshots/44444444-4444-4444-4444-444444444444`,
      },
    },
    {
      markerId: "marker-server-first",
      snapshotId: CONTRACT_SNAPSHOT_ID,
      capturedAt: "2026-06-08T01:00:05Z",
      currentWindowEndUtc: "2026-06-08T01:00:00Z",
      type: "normal",
      severity: "info",
      readMeaning: "stored_read_model_point",
      captureReason: "hourly_scheduled",
      storedApplicationStateCode: "active",
      previousState: {
        stateCode: "degraded",
        source: "dashboard_snapshots",
        snapshotId: null,
        capturedAt: null,
      },
      title: "서버가 두 번째로 준 마커",
      summary: "marker는 state source가 아니라 timeline 탐색 색인입니다.",
      recommendedAction: null,
      confidence: 0.1,
      primaryRuleId: null,
      primaryEndpointKey: null,
      links: {
        snapshot: `/api/projects/${CONTRACT_PROJECT_ID}/applications/${CONTRACT_APPLICATION_ID}/dashboard/snapshots/${CONTRACT_SNAPSHOT_ID}`,
      },
    },
  ],
};

export const snapshotDetailContractFixture: DashboardSnapshotDetailReadModel = {
  generatedAt: "2026-06-09T00:05:00Z",
  source: "dashboard_snapshots",
  readSemantics: {
    mode: "stored_snapshot_detail",
    source: "dashboard_snapshots.read_model_json",
    snapshotDetailRecalculates: false,
    currentStateRecalculated: false,
    liveSourcesJoined: [],
    rawReadModelJsonExposed: false,
    markerIsStateSource: false,
    baselineComparisonUsedForMvpDecision: false,
  },
  snapshot: {
    snapshotId: CONTRACT_SNAPSHOT_ID,
    capturedAt: "2026-06-08T01:00:00Z",
    generatedAt: "2026-06-08T01:00:05Z",
    currentWindow: {
      startUtc: "2026-06-08T00:30:00Z",
      endUtc: "2026-06-08T01:00:00Z",
    },
    baselineWindow: {
      startUtc: "2026-06-08T00:00:00Z",
      endUtc: "2026-06-08T00:30:00Z",
    },
    captureReason: "hourly_scheduled",
    storedApplicationStateCode: "active",
    primaryRuleId: null,
    primaryEndpointKey: null,
    maxConfidence: 0.1,
  },
  marker: snapshotMarkersContractFixture.markers[1],
  previousState: {
    stateCode: "degraded",
    source: "dashboard_snapshots",
    snapshotId: null,
    capturedAt: null,
  },
  lastHealthyAt: {
    value: "2026-06-08T00:59:30Z",
    source: "dashboard_snapshots",
    snapshotId: CONTRACT_SNAPSHOT_ID,
  },
  recoveryMarker: null,
  readModel: {
    schemaVersion: "dashboard_read_model.v1",
    mode: "snapshot",
    window: {
      type: "recent_30_minutes",
      startUtc: "2026-06-08T00:30:00Z",
      endUtc: "2026-06-08T01:00:00Z",
    },
    thresholds: { minimumRequestCount: 30 },
    operatorSummary: { headline: "저장된 요약" },
    dataQuality: { limitations: ["baseline_comparison_not_used_for_mvp"] },
    signals: { red: { requestCount: 91 } },
    stateReasons: [],
    attentionEvidence: [
      {
        type: "endpoint_server_error",
        severity: "attention",
        scope: "endpoint",
        target: "GET /z-contract",
        reasonCode: "snapshot_attention_evidence_stored",
        affectsLifecycleState: false,
        operatorText: "markerBucket은 normal이지만 저장본에는 500번대 attention evidence가 남아 있습니다.",
      },
    ],
    firstLookCandidates: [],
    readSemantics: {
      source: "dashboard_snapshots.read_model_json",
      snapshotDetailRecalculates: false,
      markerIsStateSource: false,
      baselineComparisonUsedForMvpDecision: false,
      histogramBucketsUsedForPercentiles: false,
      bucketDistributionSource: "accepted_bucket",
    },
    application: { name: "orders-api" },
    state: {
      code: "active",
      label: "정상",
      rationale: "저장 당시에는 state를 변경할 운영 기준 초과 신호가 없었습니다.",
      recommendedAction: "저장된 attention evidence만 확인하세요.",
      scope: "application",
    },
    starterConnection: { stateImpact: "none" },
    zeroInsight: null,
    recovery: null,
    metrics: { requestCount: 91 },
    sourceScopedPercentiles: null,
    triageCards: [],
    endpointPriority: null,
  },
  snapshotEndpointEvidence: {
    source: "dashboard_snapshots.read_model_json.endpointPriority",
    maxItems: 10,
    selectionPolicy: "stored_read_model",
    unavailableReason: null,
    items: [],
  },
  instanceSummary: {
    schemaVersion: "dashboard_read_model.v1",
    source: "dashboard_snapshots.read_model_json.instanceSummary.items",
    maxItems: 50,
    selectionPolicy: "stored_read_model",
    unavailableReason: null,
    items: [],
  },
  links: {
    self: `/api/projects/${CONTRACT_PROJECT_ID}/applications/${CONTRACT_APPLICATION_ID}/dashboard/snapshots/${CONTRACT_SNAPSHOT_ID}`,
    markers: `/api/projects/${CONTRACT_PROJECT_ID}/applications/${CONTRACT_APPLICATION_ID}/dashboard/snapshot-markers`,
  },
};

const instanceDashboardBase = {
  schemaVersion: "instance_dashboard_read_model.v1",
  generatedAt: "2026-06-09T00:05:00Z",
  application: {
    projectId: CONTRACT_PROJECT_ID,
    applicationId: CONTRACT_APPLICATION_ID,
    name: "orders-api",
    environment: "prod",
    links: {
      dashboard: `/api/projects/${CONTRACT_PROJECT_ID}/applications/${CONTRACT_APPLICATION_ID}/dashboard`,
    },
  },
  instance: {
    instanceId: CONTRACT_INSTANCE_ID,
    instanceName: "orders-api-contract-a",
    firstSeenAt: "2026-06-08T00:00:00Z",
    lastSeenAt: "2026-06-09T00:04:30Z",
  },
  thresholds: {
    minimumRequestCount: 30,
    errorRate: 0.05,
    slowShareOver500ms: 0.2,
    datasourcePoolUsage: 0.85,
    cpuUsage: 0.85,
    heapUsage: 0.9,
  },
  observationStatus: {
    code: "observed",
    reason: null,
    lastObservedBucketEndUtc: "2026-06-09T00:04:30Z",
  },
  applicationContribution: {
    level: "contributing",
    reason: "selected_instance_endpoint_server_error_observed",
    evidenceRefs: ["endpoint-evidence-z"],
  },
  dataQuality: {
    state: "sufficient",
    limitations: [],
    source: "accepted_metric_buckets",
  },
  starterConnection: {
    statusSource: "starter_heartbeat",
    lastHeartbeatAt: "2026-06-09T00:04:50Z",
    lastHeartbeatStatus: "received",
    freshnessLabel: "recent",
    connectionMeaning: "starter_connected",
    stateImpact: "does_not_change_metric_state",
  },
  signals: {
    red: {
      requestCount: 91,
      errorCount: 7,
      errorRate: 0.0769,
      slowCountOver500ms: 21,
      slowShareOver500ms: 0.2308,
      requestSymptomPresent: true,
    },
  },
  endpointEvidence: {
    source: "accepted_metric_buckets.endpoints_json",
    scope: "instance_recent_30_minutes",
    selectionPolicy: "application_evidence_presence_then_instance_symptom",
    displayOrderingPolicy: "server_order",
    status: "available",
    reason: null,
    items: [
      {
        method: "GET",
        route: "/z-contract",
        endpointKey: "GET /z-contract",
        presenceOnSelectedInstance: "observed",
        requestCount: 40,
        errorCount: 1,
        errorRate: 0.025,
        localDisplayOrder: 2,
        status: "available",
        reason: "server_projected",
        relatedApplicationEndpointEvidenceRef: "endpoint-evidence-z",
      },
      {
        method: "POST",
        route: "/a-contract",
        endpointKey: "POST /a-contract",
        presenceOnSelectedInstance: "observed",
        requestCount: 51,
        errorCount: 6,
        errorRate: 0.1176,
        localDisplayOrder: 1,
        status: "available",
        reason: "server_projected",
        relatedApplicationEndpointEvidenceRef: "endpoint-evidence-a",
      },
    ],
  },
  resourceEvidence: {
    source: "accepted_metric_buckets",
    status: "available",
    items: [
      {
        resourceKey: "heap",
        scope: "instance",
        usage: 0.91,
        threshold: 0.9,
        status: "threshold_exceeded",
        observedAt: "2026-06-09T00:04:30Z",
        requestSymptomPresent: true,
        patternContribution: "shared_resource_pressure_pattern",
        operatorText: "Heap 사용률과 요청 증상이 같은 window에서 관찰됩니다.",
      },
    ],
  },
  patterns: [
    {
      patternKey: "shared_resource_pressure_pattern",
      contribution: "shared_resource_pressure_pattern",
      evidenceRefs: ["heap"],
    },
  ],
  excludedCapabilities: [
    "instance_lifecycle_state_machine",
    "instance_health_score",
    "instance_root_cause",
    "heartbeat_as_metric_state",
  ],
};

export const instanceDashboardLiveContractFixture: InstanceDashboardReadModel = {
  ...instanceDashboardBase,
  mode: "live",
  window: {
    name: "recent_30_minutes",
    startUtc: "2026-06-08T23:35:00Z",
    endUtc: "2026-06-09T00:05:00Z",
    bucketDurationSeconds: 30,
    windowSource: "live_recent_30_minutes",
  },
  applicationStateRef: {
    lifecycleOwner: "application",
    source: "application_dashboard_live",
    applicationStateCode: "degraded",
    snapshotId: null,
  },
  snapshot: null,
  readSemantics: {
    source: "accepted_metric_buckets",
    windowSource: "live_recent_30_minutes",
    snapshotRowSource: null,
    acceptedAtCutoffApplied: false,
    includesLateAcceptedMetrics: false,
    mayDifferFromStoredApplicationSnapshot: false,
    applicationSnapshotRecalculated: false,
    instanceEvidenceReconstructedFromMetrics: false,
    markerIsStateSource: false,
  },
  links: {
    self: `/api/projects/${CONTRACT_PROJECT_ID}/applications/${CONTRACT_APPLICATION_ID}/instances/${CONTRACT_INSTANCE_ID}/dashboard`,
    applicationDashboard: `/api/projects/${CONTRACT_PROJECT_ID}/applications/${CONTRACT_APPLICATION_ID}/dashboard`,
    instanceEvidence: `/api/projects/${CONTRACT_PROJECT_ID}/applications/${CONTRACT_APPLICATION_ID}/instances/${CONTRACT_INSTANCE_ID}/evidence`,
    snapshotTrend: `/api/projects/${CONTRACT_PROJECT_ID}/applications/${CONTRACT_APPLICATION_ID}/instances/${CONTRACT_INSTANCE_ID}/snapshot-trend`,
    applicationSnapshotDetail: null,
  },
};

export const instanceDashboardSnapshotContractFixture: InstanceDashboardReadModel = {
  ...instanceDashboardBase,
  mode: "snapshot",
  window: {
    name: "recent_30_minutes",
    startUtc: "2026-06-08T00:30:00Z",
    endUtc: "2026-06-08T01:00:00Z",
    bucketDurationSeconds: 30,
    windowSource: "selected_application_snapshot",
  },
  applicationStateRef: {
    lifecycleOwner: "application",
    source: "selected_application_snapshot",
    applicationStateCode: "active",
    snapshotId: CONTRACT_SNAPSHOT_ID,
  },
  endpointEvidence: {
    ...instanceDashboardBase.endpointEvidence,
    items: [
      {
        method: "GET",
        route: "/z-contract",
        endpointKey: "GET /z-contract",
        presenceOnSelectedInstance: "not_observed",
        requestCount: 0,
        errorCount: 0,
        errorRate: null,
        localDisplayOrder: 1,
        status: "missing",
        reason: "not_observed_on_selected_instance",
        relatedApplicationEndpointEvidenceRef: "endpoint-evidence-z",
      },
    ],
  },
  snapshot: {
    snapshotId: CONTRACT_SNAPSHOT_ID,
    snapshotRowSource: "dashboard_snapshots",
    generatedAt: "2026-06-08T01:00:05Z",
    currentWindowStartUtc: "2026-06-08T00:30:00Z",
    currentWindowEndUtc: "2026-06-08T01:00:00Z",
    captureReason: "hourly_scheduled",
    storedApplicationStateCode: "active",
  },
  readSemantics: {
    source: "accepted_metric_buckets",
    windowSource: "selected_application_snapshot",
    snapshotRowSource: "dashboard_snapshots",
    acceptedAtCutoffApplied: false,
    includesLateAcceptedMetrics: true,
    mayDifferFromStoredApplicationSnapshot: true,
    applicationSnapshotRecalculated: false,
    instanceEvidenceReconstructedFromMetrics: true,
    markerIsStateSource: false,
  },
  links: {
    self: `/api/projects/${CONTRACT_PROJECT_ID}/applications/${CONTRACT_APPLICATION_ID}/snapshots/${CONTRACT_SNAPSHOT_ID}/instances/${CONTRACT_INSTANCE_ID}/dashboard`,
    applicationDashboard: `/api/projects/${CONTRACT_PROJECT_ID}/applications/${CONTRACT_APPLICATION_ID}/dashboard`,
    instanceEvidence: `/api/projects/${CONTRACT_PROJECT_ID}/applications/${CONTRACT_APPLICATION_ID}/instances/${CONTRACT_INSTANCE_ID}/evidence`,
    snapshotTrend: `/api/projects/${CONTRACT_PROJECT_ID}/applications/${CONTRACT_APPLICATION_ID}/instances/${CONTRACT_INSTANCE_ID}/snapshot-trend`,
    applicationSnapshotDetail: `/api/projects/${CONTRACT_PROJECT_ID}/applications/${CONTRACT_APPLICATION_ID}/dashboard/snapshots/${CONTRACT_SNAPSHOT_ID}`,
  },
};

export const instanceDashboardSummaryCapOutsideFixture: InstanceDashboardReadModel = {
  ...instanceDashboardSnapshotContractFixture,
  applicationContribution: {
    level: "supporting",
    reason: "selected_instance_outside_snapshot_summary_cap_reconstructed_from_metrics",
    evidenceRefs: ["accepted_metric_bucket-window-reconstruction"],
  },
  dataQuality: {
    state: "sufficient",
    limitations: [
      "stored instanceSummary.items[]에 target instance가 없어도 snapshot mode detail source는 accepted_metric_buckets입니다.",
    ],
    source: "accepted_metric_buckets",
  },
  endpointEvidence: {
    ...instanceDashboardSnapshotContractFixture.endpointEvidence,
    reason: "selected_instance_not_required_in_stored_summary",
  },
};

export const instanceDashboardRetentionGapFixture: InstanceDashboardReadModel = {
  ...instanceDashboardSnapshotContractFixture,
  observationStatus: {
    code: "metric_missing",
    reason: "selected_snapshot_instance_bucket_missing",
    lastObservedBucketEndUtc: null,
  },
  applicationContribution: {
    level: "insufficient",
    reason: "metric_missing",
    evidenceRefs: [],
  },
  dataQuality: {
    state: "metric_missing",
    limitations: ["보관 기간 안의 snapshot row는 있지만 selected instance metric evidence를 찾을 수 없습니다."],
    source: "accepted_metric_buckets",
  },
  endpointEvidence: {
    ...instanceDashboardSnapshotContractFixture.endpointEvidence,
    status: "missing",
    reason: "no_endpoint_evidence_in_window",
    items: [],
  },
  resourceEvidence: {
    source: "accepted_metric_buckets",
    status: "missing",
    items: [],
  },
  patterns: [],
};

export const instanceEvidenceContractFixture: InstanceEvidenceReadModel = {
  generatedAt: "2026-06-09T00:05:00Z",
  application: {
    projectId: CONTRACT_PROJECT_ID,
    applicationId: CONTRACT_APPLICATION_ID,
    name: "orders-api",
    environment: "prod",
    links: {
      dashboard: `/api/projects/${CONTRACT_PROJECT_ID}/applications/${CONTRACT_APPLICATION_ID}/dashboard`,
    },
  },
  instance: {
    instanceId: CONTRACT_INSTANCE_ID,
    instanceName: "orders-api-contract-a",
    firstSeenAt: "2026-06-08T00:00:00Z",
    lastSeenAt: "2026-06-09T00:04:30Z",
  },
  metricData: {
    statusSource: "accepted_bucket",
    window: {
      name: "recent_30_minutes",
      startUtc: "2026-06-08T23:35:00Z",
      endUtc: "2026-06-09T00:05:00Z",
      bucketDurationSeconds: 30,
    },
    lastAcceptedBucketAt: "2026-06-09T00:04:30Z",
    freshnessLabel: "current",
    sampleReadiness: "sufficient",
    requestCount: 91,
    errorCount: 7,
    errorRate: 0.0769,
    reason: null,
  },
  starterConnection: {
    statusSource: "starter_heartbeat",
    lastHeartbeatAt: "2026-06-09T00:04:50Z",
    lastHeartbeatStatus: "received",
    freshnessLabel: "recent",
    connectionMeaning: "starter_connected",
    stateImpact: "none",
  },
  starterPercentiles: {
    source: "starter_canonical_percentile",
    scope: "instance_bucket",
    window: "recent_30_minutes",
    bucketDurationSeconds: 30,
    maxPointCount: 60,
    displayPolicy: "source_scoped_series",
    aggregatePolicy: "no_average_no_max_no_merge_no_histogram_recalculation",
    status: "available",
    reason: null,
    points: [
      {
        bucketStartUtc: "2026-06-09T00:04:00Z",
        bucketEndUtc: "2026-06-09T00:04:30Z",
        requestCount: 41,
        p95Ms: 220,
        p99Ms: 410,
      },
    ],
  },
  histogramDistribution: {
    source: "accepted_bucket",
    scope: "instance",
    status: "available",
    reason: null,
    totalCount: 91,
    buckets: [
      { leMs: 100, count: 7 },
      { leMs: 500, count: 70 },
      { leMs: 1000, count: 91 },
    ],
  },
  resourceHints: {
    source: "accepted_bucket",
    status: "available",
    reason: null,
    bucketEndUtc: "2026-06-09T00:04:30Z",
    cpuUsageRatio: 0.42,
    heapUsedRatio: 0.52,
    datasourcePoolUsageRatio: 0.62,
  },
  applicationTriageContribution: {
    status: "contributed",
    contributed: true,
    relatedRuleIds: ["server-rule-b"],
    reason: "endpoint_evidence",
  },
  endpointEvidence: {
    source: "application_endpoint_priority",
    scope: "selected_instance",
    selectionPolicy: "server_bounded_projection",
    displayOrderingPolicy: "server_order",
    status: "available",
    reason: null,
    items: [
      {
        method: "GET",
        route: "/z-contract",
        endpointKey: "GET /z-contract",
        presenceOnSelectedInstance: "observed",
        instanceRequestCount: 40,
        instanceErrorCount: 1,
        instanceErrorRate: 0.025,
        applicationEndpointRequestCount: 40,
        applicationEndpointErrorCount: 1,
        applicationEndpointErrorRate: 0.025,
        instanceRequestShare: 0.44,
        instanceErrorShare: 0.14,
        durationBuckets: [
          { leMs: 500, count: 30 },
          { leMs: 1000, count: 40 },
        ],
        bucketDistributionSource: "accepted_bucket",
        relatedApplicationPriorityRank: 20,
        localDisplayOrder: 2,
        relatedRuleIds: ["server-rule-b"],
        status: "available",
        reason: "server_projected",
      },
      {
        method: "POST",
        route: "/a-contract",
        endpointKey: "POST /a-contract",
        presenceOnSelectedInstance: "observed",
        instanceRequestCount: 51,
        instanceErrorCount: 6,
        instanceErrorRate: 0.1176,
        applicationEndpointRequestCount: 51,
        applicationEndpointErrorCount: 6,
        applicationEndpointErrorRate: 0.1176,
        instanceRequestShare: 0.56,
        instanceErrorShare: 0.86,
        durationBuckets: [
          { leMs: 500, count: 45 },
          { leMs: 1000, count: 51 },
        ],
        bucketDistributionSource: "accepted_bucket",
        relatedApplicationPriorityRank: 10,
        localDisplayOrder: 1,
        relatedRuleIds: ["server-rule-a"],
        status: "available",
        reason: "server_projected",
      },
    ],
  },
  links: {
    self: `/api/projects/${CONTRACT_PROJECT_ID}/applications/${CONTRACT_APPLICATION_ID}/instances/${CONTRACT_INSTANCE_ID}/evidence`,
    dashboard: `/api/projects/${CONTRACT_PROJECT_ID}/applications/${CONTRACT_APPLICATION_ID}/dashboard`,
    snapshotTrend: `/api/projects/${CONTRACT_PROJECT_ID}/applications/${CONTRACT_APPLICATION_ID}/instances/${CONTRACT_INSTANCE_ID}/snapshot-trend`,
  },
};

export const instanceTrendContractFixture: InstanceSnapshotTrendReadModel = {
  generatedAt: "2026-06-09T00:05:00Z",
  application: instanceEvidenceContractFixture.application,
  instance: {
    ...instanceEvidenceContractFixture.instance,
    links: {
      evidence: instanceEvidenceContractFixture.links.self,
    },
  },
  source: "dashboard_snapshots.read_model_json.instanceSummary.items",
  horizon: {
    since: "2026-06-02T00:00:00Z",
    until: "2026-06-09T00:00:00Z",
    requestedSince: "7d",
    defaultSince: "7d",
    maxSince: "14d",
    limit: 336,
    maxLimit: 672,
    order: "currentWindowEndUtc_asc",
  },
  points: [
    {
      snapshotId: CONTRACT_SNAPSHOT_ID,
      capturedAt: "2026-06-08T01:00:00Z",
      currentWindowEndUtc: "2026-06-08T01:00:00Z",
      storedApplicationStateCode: "active",
      captureReason: "hourly_scheduled",
      instanceName: "orders-api-contract-a",
      observationStatus: "observed",
      metricData: {
        statusSource: "accepted_bucket",
        lastAcceptedBucketAt: "2026-06-08T00:59:30Z",
        freshnessLabel: "current",
      },
      starterConnection: {
        statusSource: "starter_heartbeat",
        lastHeartbeatAt: "2026-06-08T00:59:45Z",
        lastHeartbeatStatus: "received",
        connectionMeaning: "starter_connected",
        stateImpact: "none",
      },
      starterPercentilePoint: {
        source: "starter_canonical_percentile",
        scope: "instance_bucket",
        bucketStartUtc: "2026-06-08T00:59:00Z",
        bucketEndUtc: "2026-06-08T00:59:30Z",
        requestCount: 41,
        p95Ms: 220,
        p99Ms: 410,
      },
      resourceHints: {
        source: "accepted_bucket",
        status: "available",
        bucketEndUtc: "2026-06-08T00:59:30Z",
        cpuUsageRatio: 0.42,
        heapUsedRatio: 0.52,
        datasourcePoolUsageRatio: 0.62,
      },
      applicationTriageContribution: {
        status: "not_contributed",
        contributed: false,
        relatedRuleIds: [],
        reason: "no_action_needed",
      },
      endpointEvidenceRefs: [
        {
          endpointKey: "GET /z-contract",
          method: "GET",
          route: "/z-contract",
          relatedApplicationPriorityRank: 20,
          relatedRuleIds: ["server-rule-b"],
          snapshotDetailAnchor: "endpoint-z",
        },
      ],
    },
    {
      snapshotId: "44444444-4444-4444-4444-444444444444",
      capturedAt: "2026-06-08T23:00:00Z",
      currentWindowEndUtc: "2026-06-08T23:00:00Z",
      storedApplicationStateCode: "down",
      captureReason: "state_change",
      instanceName: "orders-api-contract-a",
      observationStatus: "observed",
      metricData: {
        statusSource: "accepted_bucket",
        lastAcceptedBucketAt: "2026-06-08T22:59:30Z",
        freshnessLabel: "stale",
      },
      starterConnection: {
        statusSource: "starter_heartbeat",
        lastHeartbeatAt: "2026-06-08T22:59:45Z",
        lastHeartbeatStatus: "received",
        connectionMeaning: "starter_connected",
        stateImpact: "none",
      },
      starterPercentilePoint: null,
      resourceHints: {
        source: "accepted_bucket",
        status: "missing",
        bucketEndUtc: null,
        cpuUsageRatio: null,
        heapUsedRatio: null,
        datasourcePoolUsageRatio: null,
      },
      applicationTriageContribution: {
        status: "contributed",
        contributed: true,
        relatedRuleIds: ["server-rule-a"],
        reason: "state_change",
      },
      endpointEvidenceRefs: [
        {
          endpointKey: "POST /a-contract",
          method: "POST",
          route: "/a-contract",
          relatedApplicationPriorityRank: 10,
          relatedRuleIds: ["server-rule-a"],
          snapshotDetailAnchor: "endpoint-a",
        },
      ],
    },
  ],
};
